version: "3.9"

services:
  db:
    container_name: todo-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - todo
    volumes:
      - ./pkg/storage/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - todo-postgres-data:/var/lib/postgresql/data/  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  todo-app:
    container_name: todo-app
    build: ./
    restart: always
    ports:
      - "8181:8181"
    networks:
      - todo
    depends_on:
      db:
        condition: service_healthy   

networks:
  todo:

volumes:
  todo-postgres-data:
